### ISSUE TITLE
training

### ISSUE THREAD

**Issue by vovanphuc** [XL-H/GUIE-2nd-Place-Solution#2]
Hi, I followed your instructions, but when the training loss doesn't decrease, could you please provide me with the log file so that I can compare it? Thank you.

**Comment by xiaol827** [comment]
I used to run it on a GPU platform, the instance had been released long time ago, sorry for that. Will you please provide your trainscript here in detail, see if I can get you some help~

**Comment by vovanphuc** [comment]
Thank you, I have found an error in the data preprocessing process.
